name: mary_fifi
description: Só as fofoca quente na palma da sua mão.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^2.0.1
  firebase_core: ^1.7.0
  firebase_analytics: ^8.3.3
  firebase_auth: ^3.1.3
  cloud_firestore: ^2.5.3
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  cupertino_icons: ^1.0.2
  flutter_mobx: ^2.0.2
  provider: ^6.0.0
  mobx: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2

flutter:

  uses-material-design: true

  assets:
   - assets/inicio.svg
   - assets/Logo.svg
   - assets/createRoom.svg
   - assets/Maryfifi.svg
